# Makefile for Beginning Linux Programming 3rd Edition
# Chapter 15

CLIENTS=client3
SERVERS=server3
INFO=getname getdate getdate-udp
SELECT=select

CFLAGS=
LDFLAGS=

ALL= $(CLIENTS) $(SERVERS) 

all: $(ALL)

clean:
	@rm -f $(ALL) *~ *.o
